### ISSUE TITLE
Will Netfpga-PLUS work on an alveo U50?

### ISSUE THREAD

**Issue by LTolrom** [NetFPGA/NetFPGA-PLUS#5]
Hello, 

we are about to buy an alveo U50 to experiment with Netfpga-PLUS, in the doc it says that the Alveo series is supported but the U50 is not in the list, I would like to make sure that there are no compatibility problems before buying the card?

Thanks,

Léo

**Comment by awm22** [comment]
You are quite correct; U50 is not among the supported boards.

Potts are always welcome and others will have direct advice both about the
port and the advisability or otherwise of the U50 platform.

Andrew

**Comment by LTolrom** [comment]
Hi andrew,

Thanks for your reply and sorry for my late answer. We will try to port NetFPGA PLUS to our soon ordered Alveo u50 and we will be happy to share our results.
If you or any other NetFPGA contributor have any advice for us, we will be really happy to hear it. 

Sincerely,

Léo

**Comment by m-liess** [comment]
Hi Leo, 

are there any updates on this? Especially considering advice to port the design to a different board... I recently got an Alveo U55C and am looking into porting the NetFPGA-PLUS designs. 

Best,
Marco

**Comment by LTolrom** [comment]
Hi Marco,

I just started my research for this porting because we had a lot of delay on the FPGA board/server. With my humble knowledge (I'm a working student) what I'm planning to do is to look at how the constraints file of the different alveo boards are mapped with the top module and how I can do the correlation with the constraint file of the U50. 

As the boards are from the same family I hope that it will not be harder than that. They are already some specifics adding for U50 in the top module, I think, is because of the compatibility of U50 with Open-nic (on which Netfpga is based for is NIC).

I will comment on my progress if I have any success, and will be very glad to hear your ideas.

Best,
Leo

**Comment by awm22** [comment]
HI Marco and Leo,
reallly looking forward to whatever progress you contribute, I'll close this ticket at this time.
Andrew.
